### ISSUE TITLE
image metadata

### ISSUE THREAD

**Issue by ZYecho** [ktock/container-bootfs#1]
How to deal with image metadata?
if a host want to run a image A, how does it know image A store in remote blob store or not?

**Comment by ktock** [comment]
Thanks for your feedback.

First of all, imageA (which was generated by our image converter `mkimage`, right?) itself is [Docker image spec](https://github.com/moby/moby/blob/master/image/spec/v1.2.md) compatible, so we can pull it in just the same way as normal Docker images and the container runtime determine where this image should be pulled from.

But in terms of imageA's rootfs blobs, we need to specify the location of the blob store *at runtime* (as `BLOB_STORE` environment variable) and imageA itself doesn't include any location information of these stores because it should be difficult for us to determine it at build time.
The blob store can be a local directory, ssh server or anything which desync supports and we need to specify the protocol as the address like `ssh://foo@bar/baz` (SSH server) or `/foo/bar/baz` (local directory) at runtime.
And we can also specify a directory which can be used as a local cache at runtime.

When we run a image which blobs are stored on SSH server, we need to specify something like:
```shell
sudo docker run -it --privileged --device /dev/fuse \
                --volumes-from ${LOCAL_CACHE_NAME} \
                -e BLOB_STORE=ssh://foo@bar/baz \
                -e DROPBEAR_PASSWORD=foobarbaz \
                image-a:latest
```
Note that we need to store our SSH password in `DROPBEAR_PASSWORD` environment variable.

When we run a image which blobs are stored on a local directory, we need to specify something like:
```shell
sudo docker run -it --privileged --device /dev/fuse \
                --volumes-from ${LOCAL_CACHE_NAME} \
                -v /foo/bar/baz:/store \
                -e BLOB_STORE=/store \
                image-a:latest
```
Note that we need to volume mount the directory (in this case, host's `/foo/bar/baz`).

ImageA includes an index file of the blobs (aka caidx or caibx file of casync), then desync inside imageA tries to pull blobs from the blob store specified like above, referring to the index file.
If you want to know what desync is actually doing during the pull process, please refer to [desync's repo](https://github.com/folbricht/desync).
I can say that if desync cannot pull enough blobs, it leads to failure or unstable behavior on FUSE-mounted rootfs, which means no static analysis when it FUSE-mounts rootfs and we might need to improve it.

**Comment by ZYecho** [comment]
@ktock thanks for your reply. just to confirm, without change of docker, docker doesn't know the `BLOB_STORE` environment variable, IMO, docker default pull image from registry right? who is consume the `BLOB_STORE` environment variable?

**Comment by ktock** [comment]
@ZYecho The consumer of `BLOB_STORE` is `boot` binary __inside the container__ which we generate using `mkimage` image converter. So, the `boot` binary reads the `BLOB_STORE` (specified as a runtime option) , pulls the rootfs blobs from the store (specified by `BLOB_STORE`) and then constructs his own rootfs. Docker don't need to know about `BLOB_STORE` at all, because only the `boot` program needs to know and use it. 

This means *the container's rootfs is constructed by the container itself* using `boot` binary, and this is very important point, because this is the main reason why we don't need to modify docker at all.

General procedure of running an image: 
1. First, we need to generate and load a bootfs-included [image-spec compliant](https://github.com/moby/moby/blob/master/image/spec/v1.2.md) image (we call it `boot image`) based on existing image, using `mkimage` image converter.
2. We run `boot image` using docker. At this time, we need to specify `BLOB_STORE` (store location) environment variable as a runtime option of `docker run`. Of course, in advance, we need to store the blobs (which has been generated by `mkimage` converter on the stage 1 above) in the store (specified in `BLOB_STORE`).
3. Docker simply run our `boot image` which includes `boot` binary. Then the `boot` binary pulls the blobs and constructs the rootfs, refering to `BLOB_STORE`. Finally, the original apprication is executed by `boot` binary.

As you can see, only `boot` binary inside the container consumes `BLOB_STORE` environment variable and then constructs the container's rootfs by himself.

Thank you for your confirmation.

**Comment by ZYecho** [comment]
@ktock thanks for reply, great work :) :+1:
